# ローカル開発環境とCI環境用
version: "3"
services:
  db:
    build:
      context: .
      dockerfile: "docker/db/Dockerfile"
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin!"
      POSTGRES_DB: "devdb"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      TS: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - "./.docker-compose-data/db/data:/var/lib/postgresql/data"
  app:
    build:
      context: .
      dockerfile: "docker/app/dev/Dockerfile"
    depends_on:
      - "db"
    links:
      - "db"
    environment:
      POSTGRES_NAME: "devdb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin!"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      JWT_SECRET_KEY: "samplekey"
      RUNSERVER: "LOCAL" # [LOCAL, STAGING, PRODUCTION]
    volumes:
      - ".:/go/src/github.com/gold-kou/go-housework"
      - "./go-modules:/go/pkg/mod"
      - "~/.ssh:/root/.ssh"
    ports:
      - "8080:8080"
    tty: true
  nginx:
    build:
      context: .
      dockerfile: "docker/nginx/Dockerfile"
    links:
      - "app"
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
    volumes:
      - "./nginx/dev/default.conf:/etc/nginx/conf.d/default.conf:ro" # localではdevのconfで上書き
