openapi: 3.0.0
info:
  version: 1.0.0
  title: go-housework
  description: 家事タスクを管理するAPIサーバです。
servers:
  - url: http://localhost:8080
    description: Development local server
  - url: https://XXXX.com
    description: Production server
paths:
  /health:
    get:
      summary: 死活監視API
      description: HTTPレベルでAPIサーバを死活監視するためのAPI。
      operationId: getHealth
      responses:
        '200':
          description: Success Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseGetHealth'
  /user:
    post:
      security:
        - bearerAuth: []
      summary: ユーザ登録API
      description: ユーザ情報を登録するAPI
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestCreateUser'
      responses:
        '200':
          description: Success Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseCreateUser'
        '400':
          description: Bad Request Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseBadRequest'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseInternalServerError' 
    delete:
      security:
        - bearerAuth: []
      summary: ユーザ削除API
      description: ユーザ情報(自身のみ)を削除するAPI
      operationId: deleteUser
      responses:
        '200':
          description: Success Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseDeleteUser'  
        '400':
          description: Bad Request Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseBadRequest'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseInternalServerError'    
  /password:
    put:
      security:
        - bearerAuth: []
      summary: パスワードリセットAPI
      description: パスワードをリセットするAPI
      operationId: resetPassword
      responses:
        '200':
          description: Success Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseResetPassword'  
        '400':
          description: Bad Request Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseBadRequest'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseInternalServerError'
  /login:
    post:
      summary: ログインAPI
      description: ログインAPI
      operationId: login
      parameters:
        - in: query
          name: email
          description: Email
          required: true
          schema:
            type: string
            example: 'test@example.com'
        - in: query
          name: password
          description: Password
          required: true
          schema:
            type: string
            example: '1234'    
      responses:
        '200':
          description: Success Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseLogin'  
        '400':
          description: Bad Request Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseBadRequest'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseInternalServerError'
  /family:
    post:
      security:
        - bearerAuth: []
      summary: 世帯登録API
      description: 世帯を登録するAPI。登録者が世帯管理者となる。世帯管理者は変更できない。
      operationId: createFamily
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestCreateFamily'
      responses:
        '200':
          description: Success Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseCreateFamily'  
        '400':
          description: Bad Request Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseBadRequest'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseInternalServerError'
    get:
      security:
        - bearerAuth: []
      summary: 世帯詳細情報取得API
      description: 世帯詳細情報を取得するAPI。世帯管理者のみ実行可能。
      operationId: showFamily
      responses:
        '200':
          description: Success Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseShowFamily'  
        '400':
          description: Bad Request Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseBadRequest'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseInternalServerError'
    update:
      security:
        - bearerAuth: []
      summary: 世帯情報更新API
      description: 世帯情報を更新するAPI。世帯管理者のみ実行可能。
      operationId: updateFamily
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestUpdateFamily'
      responses:
        '200':
          description: Success Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseUpdateFamily'  
        '400':
          description: Bad Request Response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseBadRequest'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ResponseInternalServerError'
components:
  securitySchemes:
    bearerAuth:
      description: JWT
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RequestCreateUser:
      description: createUserのリクエストスキーマ
      type: object
      properties:
        email:
          description: Email
          type: string
          example: 'test@example.com'
        user_name:
          description: ユーザ名
          type: string
          example: 'test'
        password:
          description: パスワード
          type: string
          example: '1234'
      required:
        - email
        - user_name
        - password
    RequestCreateFamily:
      description: createFamilyのリクエストスキーマ
      type: object
      properties:
        family_name:
          description: 家族名
          type: string
          example: 'James'
      required:
        - family_name
    RequestUpdateFamily:
      description: updateFamilyのリクエストスキーマ。現状、家族名のみ変更可能なため、family_nameを必須プロパティとしている。
      type: object
      properties:
        family_name:
          description: 家族名
          type: string
          example: 'James'
      required:
        - family_name
    ResponseGetHealth:
      description: ヘルスチェックAPIの正常系レスポンススキーマ
      type: object
      properties:
        message:
          description: HTTPレスポンスメッセージ
          type: string
          example: 'The health check is clear.'
      required:
        - message
    ResponseCreateUser:
      description: ユーザ登録APIの正常系レスポンススキーマ
      type: object
      properties:
        message:
          description: HTTPレスポンスメッセージ
          type: string
          example: 'The user registration is completed.'
      required:
        - message
    ResponseDeleteUser:
      description: ユーザ削除APIの正常系レスポンススキーマ
      type: object
      properties:
        message:
          description: HTTPレスポンスメッセージ
          type: string
          example: 'The user delete is completed.'
      required:
        - message
    ResponseResetPassword:
      description: パスワードリセットAPIの正常系レスポンススキーマ
      type: object
      properties:
        message:
          description: HTTPレスポンスメッセージ
          type: string
          example: 'The password reset is completed.'
      required:
        - message
    ResponseLogin:
      description: ログインAPIの正常系レスポンススキーマ
      type: object
      properties:
        message:
          description: HTTPレスポンスメッセージ
          type: string
          example: 'Login successed.'
      required:
        - message
    ResponseCreateFamily:
      description: 世帯登録APIの正常系レスポンススキーマ
      type: object
      properties:
        family_id:
          description: 家族ID。UUID。
          type: string
          example: '342a0640-8443-462f-afd0-93940c9278f5'
        family_name: 
          description: 家族名
          type: string
          example: 'James'
      required:
        - family_id
        - family_name
    ResponseUpdateFamily:
      description: 世帯更新APIの正常系レスポンススキーマ
      type: object
      properties:
        family_id:
          description: 家族ID。UUID。
          type: string
          example: '342a0640-8443-462f-afd0-93940c9278f5'
        family_name: 
          description: 家族名
          type: string
          example: 'James'
      required:
        - family_id
        - family_name
    ResponseShowFamily:
      description: 世帯詳細情報取得APIの正常系レスポンススキーマ
      type: object
      properties:
        family_id:
          description: 家族ID。UUID。
          type: string
          example: '342a0640-8443-462f-afd0-93940c9278f5'
        family_name: 
          description: 家族名
          type: string
          example: 'James'
        members:
          description: 家族構成員情報の集合
          type: array
          items:
            $ref: '#/components/schemas/Member'  
      required:
        - family_id
        - family_name
        - members
    Member:
      description: Memberスキーマ
      type: object
      properties:
        member_id:
          description: 家族構成員ID
          type: integer
          format: int64
          example: 1
        member_name:
          description: 家族構成員名。ユーザ名と一致する。
          type: string
          example: 'LeBron'
      required:
        - member_id
        - member_name  
    ResponseBadRequest:
      description: Bad Reqeust
      type: object
      properties:
        message:
          description: HTTPレスポンスメッセージ
          type: string
          example: 'Something Bad Request Error'
      required:
        - message
    ResponseUnauthorized:
      description: Unauthorized
      type: object
      properties:
        message:
          description: HTTPレスポンスメッセージ
          type: string
          example: 'Something Unauthorized Error'
      required:
        - message
    ResponseNotFound:
      description: Not Found
      type: object
      properties:
        message:
          description: HTTPレスポンスメッセージ
          type: string
          example: 'Something Not Found Error'
      required:
        - message
    ResponseInternalServerError:
      description: Internal Server Error
      type: object
      properties:
        message:
          description: HTTPレスポンスメッセージ
          type: string
          example: 'Something Internal Server Error'
      required:
        - message    
