version: 2
jobs:
  test-all:
    machine: true
    steps:
      - checkout
      - run:
          name: docker-compose up
          command: docker-compose up -d --build
      - run:
          name: mod download
          command: docker-compose exec app make mod-download
      - run:
          name: make lint
          command: docker-compose exec app make lint
      - run:
          name: wait for postgresql
          command: sleep 10
      - run:
          name: make migrate
          command: docker-compose exec app make migrate
      - run:
          name: make test
          command: docker-compose exec app make test
      - store_artifacts:
          path: coverage.html
          destination: coverage.html
workflows:
  version: 2
  build-test:
    jobs:
      - test-all
