// Code generated by MockGen. DO NOT EDIT.
// Source: token.go

// Package middleware is a generated GoMock package.
package middleware

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/gold-kou/go-housework/app/model"
	http "net/http"
	reflect "reflect"
)

// MockTokenInterface is a mock of TokenInterface interface
type MockTokenInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTokenInterfaceMockRecorder
}

// MockTokenInterfaceMockRecorder is the mock recorder for MockTokenInterface
type MockTokenInterfaceMockRecorder struct {
	mock *MockTokenInterface
}

// NewMockTokenInterface creates a new mock instance
func NewMockTokenInterface(ctrl *gomock.Controller) *MockTokenInterface {
	mock := &MockTokenInterface{ctrl: ctrl}
	mock.recorder = &MockTokenInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTokenInterface) EXPECT() *MockTokenInterfaceMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method
func (m *MockTokenInterface) GenerateToken(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken
func (mr *MockTokenInterfaceMockRecorder) GenerateToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockTokenInterface)(nil).GenerateToken), arg0)
}

// VerifyHeaderToken mocks base method
func (m *MockTokenInterface) VerifyHeaderToken(arg0 *http.Request) (*model.Auth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyHeaderToken", arg0)
	ret0, _ := ret[0].(*model.Auth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyHeaderToken indicates an expected call of VerifyHeaderToken
func (mr *MockTokenInterfaceMockRecorder) VerifyHeaderToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyHeaderToken", reflect.TypeOf((*MockTokenInterface)(nil).VerifyHeaderToken), arg0)
}
