// Code generated by MockGen. DO NOT EDIT.
// Source: create_task.go

// Package service is a generated GoMock package.
package service

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/gold-kou/go-housework/app/model"
	db "github.com/gold-kou/go-housework/app/model/db"
	schemamodel "github.com/gold-kou/go-housework/app/model/schemamodel"
	reflect "reflect"
)

// MockCreateTaskServiceInterface is a mock of CreateTaskServiceInterface interface
type MockCreateTaskServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCreateTaskServiceInterfaceMockRecorder
}

// MockCreateTaskServiceInterfaceMockRecorder is the mock recorder for MockCreateTaskServiceInterface
type MockCreateTaskServiceInterfaceMockRecorder struct {
	mock *MockCreateTaskServiceInterface
}

// NewMockCreateTaskServiceInterface creates a new mock instance
func NewMockCreateTaskServiceInterface(ctrl *gomock.Controller) *MockCreateTaskServiceInterface {
	mock := &MockCreateTaskServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCreateTaskServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCreateTaskServiceInterface) EXPECT() *MockCreateTaskServiceInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method
func (m *MockCreateTaskServiceInterface) Execute(arg0 *model.Auth, arg1 *schemamodel.RequestCreateTask) (*db.User, *db.Family, *db.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*db.User)
	ret1, _ := ret[1].(*db.Family)
	ret2, _ := ret[2].(*db.Task)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Execute indicates an expected call of Execute
func (mr *MockCreateTaskServiceInterfaceMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateTaskServiceInterface)(nil).Execute), arg0, arg1)
}
