// Code generated by MockGen. DO NOT EDIT.
// Source: register_family_member.go

// Package service is a generated GoMock package.
package service

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/gold-kou/go-housework/app/model"
	db "github.com/gold-kou/go-housework/app/model/db"
	schemamodel "github.com/gold-kou/go-housework/app/model/schemamodel"
	reflect "reflect"
)

// MockRegisterFamilyMemberServiceInterface is a mock of RegisterFamilyMemberServiceInterface interface
type MockRegisterFamilyMemberServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRegisterFamilyMemberServiceInterfaceMockRecorder
}

// MockRegisterFamilyMemberServiceInterfaceMockRecorder is the mock recorder for MockRegisterFamilyMemberServiceInterface
type MockRegisterFamilyMemberServiceInterfaceMockRecorder struct {
	mock *MockRegisterFamilyMemberServiceInterface
}

// NewMockRegisterFamilyMemberServiceInterface creates a new mock instance
func NewMockRegisterFamilyMemberServiceInterface(ctrl *gomock.Controller) *MockRegisterFamilyMemberServiceInterface {
	mock := &MockRegisterFamilyMemberServiceInterface{ctrl: ctrl}
	mock.recorder = &MockRegisterFamilyMemberServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRegisterFamilyMemberServiceInterface) EXPECT() *MockRegisterFamilyMemberServiceInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method
func (m *MockRegisterFamilyMemberServiceInterface) Execute(arg0 *model.Auth, arg1 *schemamodel.RequestRegisterFamilyMember) (*db.User, *db.Family, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*db.User)
	ret1, _ := ret[1].(*db.Family)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Execute indicates an expected call of Execute
func (mr *MockRegisterFamilyMemberServiceInterfaceMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRegisterFamilyMemberServiceInterface)(nil).Execute), arg0, arg1)
}
