// Code generated by MockGen. DO NOT EDIT.
// Source: delete_family_member.go

// Package service is a generated GoMock package.
package service

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/gold-kou/go-housework/app/model"
	reflect "reflect"
)

// MockDeleteFamilyMemberServiceInterface is a mock of DeleteFamilyMemberServiceInterface interface
type MockDeleteFamilyMemberServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteFamilyMemberServiceInterfaceMockRecorder
}

// MockDeleteFamilyMemberServiceInterfaceMockRecorder is the mock recorder for MockDeleteFamilyMemberServiceInterface
type MockDeleteFamilyMemberServiceInterfaceMockRecorder struct {
	mock *MockDeleteFamilyMemberServiceInterface
}

// NewMockDeleteFamilyMemberServiceInterface creates a new mock instance
func NewMockDeleteFamilyMemberServiceInterface(ctrl *gomock.Controller) *MockDeleteFamilyMemberServiceInterface {
	mock := &MockDeleteFamilyMemberServiceInterface{ctrl: ctrl}
	mock.recorder = &MockDeleteFamilyMemberServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDeleteFamilyMemberServiceInterface) EXPECT() *MockDeleteFamilyMemberServiceInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method
func (m *MockDeleteFamilyMemberServiceInterface) Execute(arg0 *model.Auth, arg1 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute
func (mr *MockDeleteFamilyMemberServiceInterfaceMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteFamilyMemberServiceInterface)(nil).Execute), arg0, arg1)
}
