// Code generated by MockGen. DO NOT EDIT.
// Source: list_family_members.go

// Package service is a generated GoMock package.
package service

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/gold-kou/go-housework/app/model"
	db "github.com/gold-kou/go-housework/app/model/db"
	reflect "reflect"
)

// MockListFamilyMembersServiceInterface is a mock of ListFamilyMembersServiceInterface interface
type MockListFamilyMembersServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockListFamilyMembersServiceInterfaceMockRecorder
}

// MockListFamilyMembersServiceInterfaceMockRecorder is the mock recorder for MockListFamilyMembersServiceInterface
type MockListFamilyMembersServiceInterfaceMockRecorder struct {
	mock *MockListFamilyMembersServiceInterface
}

// NewMockListFamilyMembersServiceInterface creates a new mock instance
func NewMockListFamilyMembersServiceInterface(ctrl *gomock.Controller) *MockListFamilyMembersServiceInterface {
	mock := &MockListFamilyMembersServiceInterface{ctrl: ctrl}
	mock.recorder = &MockListFamilyMembersServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockListFamilyMembersServiceInterface) EXPECT() *MockListFamilyMembersServiceInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method
func (m *MockListFamilyMembersServiceInterface) Execute(arg0 *model.Auth) (*db.Family, []*db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0)
	ret0, _ := ret[0].(*db.Family)
	ret1, _ := ret[1].([]*db.User)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Execute indicates an expected call of Execute
func (mr *MockListFamilyMembersServiceInterfaceMockRecorder) Execute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListFamilyMembersServiceInterface)(nil).Execute), arg0)
}
