/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// ResponseLogin - ログインAPIの正常系レスポンススキーマ
type ResponseLogin struct {

	// token
	Token string `json:"token"`
}
