/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// ResponseShowFamily - 世帯詳細情報取得APIの正常系レスポンススキーマ
type ResponseShowFamily struct {

	Family Family `json:"family"`
}
