/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// User - Userスキーマ
type User struct {

	// ユーザID。メンバIDと一致する。
	UserId int64 `json:"user_id,omitempty"`

	// ユーザ名。メンバ名と一致する。
	UserName string `json:"user_name,omitempty"`
}
