/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// RequestRegisterFamilyMember - registerFamilyMemberのリクエストスキーマ
type RequestRegisterFamilyMember struct {

	// メンバ名。ユーザ名と一致。
	MemberName string `json:"member_name"`
}
