/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// ResponseListFamilyMembers - 世帯メンバ情報一覧取得APIの正常系レスポンススキーマ
type ResponseListFamilyMembers struct {

	Family Family `json:"family"`

	// 家族メンバ情報の集合
	Members []Member `json:"members"`
}
