/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// ResponseCreateFamily - 世帯登録APIの正常系レスポンススキーマ
type ResponseCreateFamily struct {

	Family Family `json:"family"`
}
