/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// ResponseCreateUser - ユーザ登録APIの正常系レスポンススキーマ
type ResponseCreateUser struct {

	User User `json:"user"`
}
