/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// ResponseDeleteTask - 世帯メンバ削除APIの正常系レスポンススキーマ
type ResponseDeleteTask struct {

	Task Task `json:"task"`

	// HTTPレスポンスメッセージ
	Message string `json:"message"`
}
