/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// ResponseDeleteFamily - 世帯削除APIの正常系レスポンススキーマ
type ResponseDeleteFamily struct {

	Family Family `json:"family"`

	// HTTPレスポンスメッセージ
	Message string `json:"message"`
}
