/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// ResponseListTasks - 家事タスク一覧取得APIの正常系レスポンススキーマ
type ResponseListTasks struct {

	Family Family `json:"family"`

	// 家事タスク情報の集合
	Tasks []Task `json:"tasks"`
}
