/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// RequestResetPassword - createUserのリクエストスキーマ
type RequestResetPassword struct {

	// Email
	Email string `json:"email"`
}
