/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// ResponseUpdateFamily - 世帯更新APIの正常系レスポンススキーマ
type ResponseUpdateFamily struct {

	Family Family `json:"family"`
}
