/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// RequestUpdateTask - updateTaskのリクエストスキーマ
type RequestUpdateTask struct {

	Task Task `json:"task"`
}
