/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// Task - Taskスキーマ
type Task struct {

	// 家事タスクID
	TaskId int64 `json:"task_id"`

	// 家事タスク名
	TaskName string `json:"task_name"`

	// ユーザ名。家事の担当者。
	MemberName string `json:"member_name"`

	// 家事進捗ステータス
	Status string `json:"status"`

	// 担当日付
	Date string `json:"date"`
}
