/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// ResponseGetHealth - ヘルスチェックAPIの正常系レスポンススキーマ
type ResponseGetHealth struct {

	// HTTPレスポンスメッセージ
	Message string `json:"message"`
}
