/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// RequestCreateUser - createUserのリクエストスキーマ
type RequestCreateUser struct {

	// Email
	Email string `json:"email"`

	// ユーザ名
	UserName string `json:"user_name"`

	// パスワード
	Password string `json:"password"`
}
