/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// ResponseCreateTask - 家事タスク作成APIの正常系レスポンススキーマ
type ResponseCreateTask struct {

	Family Family `json:"family"`

	Task Task `json:"task"`
}
