/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// Family - Familyスキーマ
type Family struct {

	// 家族ID
	FamilyId int64 `json:"family_id"`

	// 家族名
	FamilyName string `json:"family_name"`
}
