/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// ResponseUpdateTask - 家事タスク更新APIの正常系レスポンススキーマ
type ResponseUpdateTask struct {

	Family Family `json:"family"`

	Task Task `json:"task"`
}
