/*
 * go-housework
 *
 * 家事タスクを管理するAPIサーバです。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemamodel

// RequestUpdateFamily - updateFamilyのリクエストスキーマ。現状、家族名のみ変更可能なため、family_nameを必須プロパティとしている。
type RequestUpdateFamily struct {

	// 家族名
	FamilyName string `json:"family_name"`
}
